#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'iptables'

cookbook 'hdp-repo', :git => 'https://github.com/dstreev/chef_recipes', :path => 'hdp-repo', :ref => "hdp-repo_v0.1"
