#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'emacs'
cookbook 'ntp'
cookbook 'selinux'
cookbook 'vim'
cookbook 'yumrepo'

cookbook 'iptables', :git => 'https://github.com/opscode-cookbooks/iptables'
cookbook 'java', :git => 'https://github.com/opscode-cookbooks/java'
