# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

boxes = [
         #{:name => "c1repo", :ipaddress => "192.168.90.6", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c1gw", :ipaddress => "192.168.90.10", :roles => ["base", "ambari"], :recipes => ["tomcat"], :json => {}},
         {:name => "c1nn", :ipaddress => "192.168.90.11", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c1jt", :ipaddress => "192.168.90.12", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c1dn1", :ipaddress => "192.168.90.15", :roles => ["base"], :recipes => ["tomcat"], :json => {}},
         {:name => "c1dn2", :ipaddress => "192.168.90.16", :roles => ["base"], :recipes => ["tomcat"], :json => {}},
         {:name => "c1dn3", :ipaddress => "192.168.90.17", :roles => ["base"], :recipes => ["tomcat"], :json => {}},
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.ssh.private_key_path = "/Users/%s/.ssh/vagrant" % ENV['USER'].to_s
#   config.ssh.private_key_path = "/Users/" + ENV['USER'] + "/.ssh/vagrant"
  config.ssh.username = "vagrant"
  
  config.vm.provision :hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  boxes.each do |opts|
    config.vm.define opts[:name] do |vmconfig|
      # CentOS 6.4 x86_64 Minimal (VirtualBox Guest Additions 4.2.12, Chef 11.4.4, Puppet 3.1.1)
      vmconfig.vm.box = "CentOS_64_x64"
#       vmconfig.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

      vmconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", 1024]
      end

      # uncomment the line below to set up the ambari dev environment
      # vmconfig.vm.provision :shell, :path => "dev-bootstrap.sh"

      vmconfig.vm.hostname = "%s.hortonworks.vagrant" % opts[:name].to_s
      vmconfig.vm.network :private_network, ip: opts[:ipaddress]

      vmconfig.vm.provision :chef_solo do |chef|
	    chef.arguments = '-l debug'
        chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
        chef.data_bags_path = "databags"
        chef.roles_path = "roles"
		
        opts[:roles].each do |role|
          chef.add_role(role)
        end

        opts[:recipes].each do |recipe|
          chef.add_recipe(recipe)
        end
        
#         chef.json = {
#     		"authorization" => {
#         		"sudo" => {
#             		"users" => [ "vagrant" ],
#             		"passwordless" => true,
#         		}
#     		}
#   		}
      end
    end
  end
end
