#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'emacs'
cookbook 'ntp'

# Currently required since that latest 0.6.0 and 0.6.1 versions are broken for selinux::disabled
# This reference is for 0.5.6.
cookbook 'selinux', :git => 'https://github.com/opscode-cookbooks/selinux', :ref => "9350fb2e1a095fcc582b607aadcfef3614926a44"

cookbook 'vim'
cookbook 'yumrepo'

cookbook 'iptables'
cookbook 'java'

# cookbook 'ambari'
cookbook 'hostsfile', :git => 'https://github.com/customink-webops/hostsfile'

cookbook 'ambari', :git => 'https://github.com/dstreev/chef_recipes', :path => 'ambari', :ref => "ambari_v0.2"

cookbook 'hdp-prep', :git => 'https://github.com/dstreev/chef_recipes', :path => 'hdp-prep', :ref => "hdp-prep_v0.3"
cookbook 'host-entry', :git => 'https://github.com/dstreev/chef_recipes', :path => 'host-entry', :ref => "host-entry_v0.1"